# General
set -g default-terminal 'tmux-256color'
set -ga terminal-overrides ',*:RGB'
set -g mouse on
set -g set-clipboard on
set-window-option -g xterm-keys on

# Colors
thm_bg='#22272E'
thm_fg='#E4E4E4'
thm_gray='#585858'
thm_red='#F47067'
thm_green='#4CAF50'
thm_blue='#6CB6FF'

# Messages
set -g message-style "fg=${thm_fg},align=centre"
set -g message-command-style "fg=${thm_fg},align=centre"

# Status
set -g status 2
set -g status-format[1] ""
set -g status-style fg=default,bg=default
set -g status-position top
set -g status-interval 1
set -g status-left-length 100
set -g status-right-length 100

# Status (left side)
set -g status-left "#{?client_prefix,#[fg=${thm_red}],#[fg=${thm_fg}]}#[bg=${thm_bg}]#{?client_prefix,#[bg=${thm_red}],#[bg=${thm_fg}]}#[fg=${thm_bg}] #[fg=${thm_fg},bg=${thm_gray}] #S#[fg=${thm_gray},bg=${thm_bg}]"

# Status - Windows (left side)
set -g window-status-separator ''
set -g window-status-activity-style "fg=${thm_fg},bg=${thm_bg},none"
set -g window-status-style "fg=${thm_fg},bg=${thm_bg},none"
set -g window-status-current-format " #[fg=${thm_green}]#[bg=${thm_bg}]#[fg=${thm_bg},bg=${thm_green}]#I #[fg=${thm_fg},bg=${thm_gray}] #(echo '#{pane_current_path}' | rev | cut -d'/' -f-2 | rev)#[fg=${thm_gray},bg=${thm_bg}]"
set -g window-status-format " #[fg=${thm_fg}]#[bg=${thm_bg}]#[fg=${thm_bg},bg=${thm_fg}]#I #[fg=${thm_fg},bg=${thm_gray}] #W#[fg=${thm_gray},bg=${thm_bg}]"

# Status (right side)
set -g status-right " #[fg=${thm_fg},bg=${thm_bg}]#[fg=${thm_bg},bg=${thm_fg}] #[fg=${thm_fg},bg=${thm_gray}] #(kubectl config current-context || echo -)#[fg=${thm_gray},bg=${thm_bg}]"
set -ag status-right " #[fg=${thm_fg},bg=${thm_bg}]#[fg=${thm_bg},bg=${thm_fg}] #[fg=${thm_fg},bg=${thm_gray}] #(whoami || echo -)@#(hostname || echo -)#[fg=${thm_gray},bg=${thm_bg}]"
set -ag status-right " #[fg=${thm_fg},bg=${thm_bg}]#[fg=${thm_bg},bg=${thm_fg}] #[fg=${thm_fg},bg=${thm_gray}] #(date +'%a %b %d %I:%M %p')#[fg=${thm_gray},bg=${thm_bg}]"

# Panes
set -g pane-border-style "fg=${thm_gray}"
set -g pane-active-border-style "fg=${thm_fg}"

# TODO: investigate why these don't work
# Meta + Arrow keys to switch panes
# bind -n M-Left  select-pane -L
# bind -n M-Right select-pane -R
# bind -n M-Up    select-pane -U
# bind -n M-Down  select-pane -D

# Meta + [number] keys to switch window
bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9

# Splitting
unbind '"'
unbind %
bind -  split-window -v -c "#{pane_current_path}"
bind \\ split-window -h -c "#{pane_current_path}"
bind _ select-layout even-horizontal
bind | select-layout even-horizontal
bind + select-layout tiled

# New windows
bind c new-window -c "#{pane_current_path}"

# Start numbering at 1
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Popups
bind C-k display-popup -w 80% -h 80% -E "k9s"

# Reload
unbind r
bind r source-file ~/.config/tmux/tmux.conf
